DOMAIN = "battery_status_manager"

CONF_SCOPE = "scope"
CONF_MONITORED_ENTITIES = "monitored_entities"
CONF_MONITORED_DEVICES = "monitored_devices"
CONF_LOW_BATTERY_THRESHOLD = "low_battery_threshold"
CONF_ENABLE_LOW_BATTERY_NOTIFICATION = "enable_low_battery_notification"
CONF_ENABLE_DROP_NOTIFICATION = "enable_drop_notification"
CONF_DROP_THRESHOLD = "drop_threshold"
CONF_DROP_TIMEFRAME = "drop_timeframe"
CONF_NOTIFICATION_SERVICES = "notification_services"
CONF_NOTIFICATION_TITLE = "notification_title"

SCOPE_ALL = "all"
SCOPE_BY_DEVICE = "by_device"
SCOPE_BY_ENTITY = "by_entity"

DEFAULT_LOW_BATTERY_THRESHOLD = 20
DEFAULT_ENABLE_LOW_BATTERY = True
DEFAULT_ENABLE_DROP = False
DEFAULT_DROP_THRESHOLD = 20
DEFAULT_DROP_TIMEFRAME = 24
DEFAULT_NOTIFICATION_TITLE = "Battery Status Manager"
DEFAULT_SCAN_INTERVAL = 3600

STORAGE_KEY = "battery_status_manager"
STORAGE_VERSION = 1

LOW_BATTERY_HYSTERESIS = 5
